argoCD:

  # Git specific credentials, used by ArgoCD to watch the KubeAid and KubeAid Config repositories.
  # 
  # NOTE : We enforce the user, not to make ArgoCD use SSH authentication against the Git server,
  #        since : that way, ArgoCD gets both read and write permissions.
  # 
  git:

    username:

    password:

aws:

  accessKeyID:

  secretAccessKey:

  sessionToken:

azure:

  clientID:

  clientSecret:

hetzner:

  apiToken:

  robot:

    user:

    password:

